[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm --title kitty-dropterm"
class = "kitty-dropterm"
size = "75% 50%"                                                # percent of full screen
max_size = "1920px 100%"
margin = "9%"                                                   # percent of half screen
offset = "212%"                                                 # percent of half size, offset = (2*size + margin)/size

[scratchpads.dropbtop]
animation = "fromBottom"
command = "kitty --class kitty-btop --title kitty-btop btop"
class = "kitty-btop"
size = "75% 75%"                                             # percent of full screen
max_size = "1920px 100%"
margin = "25%"                                               # percent of half screen
offset = "233%"                                              # percent of half size, offset = (2*size + margin)/size

[scratchpads.qalculate]
animation = "fromLeft"
command = "qalculate-gtk"
class = "qalculate-gtk"
size = "40% 50%"          # percent of full screen
lazy = true
margin = "2%"             # percent of half screen
offset = "205%"           # percent of half size, offset = (2*size + margin)/size
